{
  imports = [
    ./apps/default.nix
    ./ashell/default.nix
    ./bash/default.nix
    ./btop/default.nix
    ./dunst/default.nix
    ./gaming/default.nix
    ./git/default.nix
    ./haskell/default.nix
    ./hyprland/default.nix
    ./hyprpaper/default.nix
    ./hyprsunset/default.nix
    ./kitty/default.nix
    ./music/default.nix
    ./nixcord/default.nix
    ./rstudio/default.nix
    ./stylix/default.nix
    ./theming/default.nix
    ./vscode/default.nix
    ./waybar/default.nix
    ./wofi/default.nix
  ];
}
