# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ 
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { 
      device = "/dev/mapper/luks-5755fbdb-f491-4b83-9453-2a5c40ac355e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5755fbdb-f491-4b83-9453-2a5c40ac355e".device = "/dev/disk/by-uuid/5755fbdb-f491-4b83-9453-2a5c40ac355e";

  fileSystems."/boot" =
    { 
      device = "/dev/disk/by-uuid/BD68-46D9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-780c6648-d69b-4952-985d-ce6cee1e7fb7"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
