animations {
  # Bezier curves
  bezier=linear,0,0,1,1
  bezier=easeInOutBack, 0.68, -0.6, 0.32, 1.6
  bezier=easeInOutSine, 0.37, 0, 0.63, 1
  bezier=easeInExpo, 0.7, 0, 0.84, 0
  bezier=easeOutQuart, 0.25, 1, 0.5, 1
  bezier=easeOutExpo, 0.16, 1, 0.3, 1
  bezier=easeOutExpoOvershoot, 0.16, 1, 0.3, 1.05
  bezier=easeOutCirc, 0.85, 0, 0.15, 1
  bezier=bouncyThing, 0.15, 0.60, 0.66, -0.61

  # Animations
  animation=windowsIn, 1, 2.5, easeOutExpo, popin
  animation=windowsIn, 1, 2.5, easeOutExpo, popin
  animation=windowsOut, 1, 4, easeOutExpo, popin 10%
  animation=windowsMove, 1, 0.9, easeOutExpo
  animation=workspaces, 1, 1.4, easeInOutSine, slidefade 50%
  animation=specialWorkspaceIn, 1, 2.8, easeOutExpoOvershoot, slide top
  animation=specialWorkspaceOut, 1, 5, easeInOutBack, slide bottom

  workspace_wraparound=true
}

# hyprlang if SLEEPLESS
animations:enabled = false
# hyprlang endif

