### EXECUTE ON BOOT ###
exec-once = hyprctl reload
exec-once=runapp soteria
exec-once=runapp kitty --class kitty-nvim --config ~/.files/modules/hjem/kitty/nvim.conf nvim
exec-once=runapp quickshell
exec-once=runapp lollypop

# hyprlang if SLEEPLESS
exec-once=[workspace 1; float; size 1463 1023; move 444 44] firefox
exec-once=vesktop & mprisence & nicotine -s
exec-once=bash ~/.files/modules/hjem/hyprland/scripts/raiseonhover.sh
exec-once=sleep 5; hyprctl --batch 'dispatch tagwindow +firefox class:firefox; dispatch tagwindow +vesktop class:vesktop'
# hyprlang endif
