### LOOK & FEEL ###
general {
  col.active_border=rgb(2A7B9B)
  col.inactive_border=rgb(072242)
  gaps_in=5
  gaps_out=5,10,10,10

  border_size=3
  resize_on_border=true
  hover_icon_on_border=true
  extend_border_grab_area=25

  layout=dwindle
  allow_tearing=false
}

# hyprlang if SLEEPLESS
monitor = eDP-1, 1920x1080, 0x0, 1.2
# hyprlang endif

decoration {
  blur {
    special=true
  }

  dim_inactive=true
  dim_strength=0.350000
  dim_special=0.6

  rounding=15
  rounding_power=1.2
}

misc {
  enable_swallow=true
  swallow_regex =^(kitty)$
  close_special_on_empty=false
  disable_watchdog_warning=true
}

xwayland {
  force_zero_scaling = 1
}
