### INPUT ###
input {
  follow_mouse=1
  kb_layout=eu
  kb_options=ctrl:swapcaps
  kb_variant=
}

# Gestures for sleepless
gesture = 3, horizontal, workspace
#gesture = 3, up, close
gesture = 3, swipe, mod: ALT, resize

# hyprlang if $HOST
gesture=3,up,close
# hyprlang endif

