### WINDOW RULES ###
windowrule = tag +defFloat, match:title Open.*
windowrule = tag +defFloat, match:title File Upload.*
windowrule = tag +defFloat, match:title Select what to share
windowrule = tag +defFloat, match:class org.pulseaudio.pavucontrol
windowrule = tag +defFloat, match:class nwg-look
windowrule = tag +defFloat, match:title File Operation Progress
windowrule = workspace 2 silent, match:class kitty-nvim

windowrule {
  name=opacityRules
  match:class=negative:kitty
  opacity=0.96 0.75
}
windowrule {
  name=vesktop behaviour
  float=on
  match:class=vesktop
  move=12 44
  size=1463 1023
  match:workspace=1
}

windowrule {
  name=Default Float Behaviour
  float=on
  match:tag=defFloat
  size=(monitor_w*0.75) (monitor_h*0.75)
  pin=on
}
windowrule {
  name=Lollypop float
  float=on
  match:class=lollypop
  size=(monitor_w*0.9) (monitor_h*0.9)
  workspace=special:music silent
}

### LAYER RULES ###
layerrule=match:class selector, no_anim on # fix for weird 1px black border on screenshots

