### WORKSPACE RULES ###
workspace = 3, persistent:true
workspace = 4, persistent:true, layout:monocle
workspace = 5, persistent:true, layout:scrolling
workspace = 9, persistent:true, rounding:false, bordersize:2, defaultName:submenus

### LAYOUT ###
dwindle {
  preserve_split = true
  pseudotile = true
  smart_split = true
}

