gesture = 3, horizontal, workspace
gesture = 3, up, close
gesture = 3, swipe, mod: ALT, resize

bindel = ,XF86MonBrightnessUp, exec, brightnessctl -q -n s +10%
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -q -n s 10%-

exec-once=runapp firefox -P "default" --no-remote --class=cheese
exec-once=runapp lollypop

windowrule {
  name=Lollypop float
  float=on
  match:class=lollypop
  size=(monitor_w*0.9) (monitor_h*0.9)
  workspace=special:music silent
}

# Battery life preservation
general {
  col.active_border = rgb(2A7B9B)
  col.inactive_border = rgba(000000E6)
}

decoration  {
  blur:enabled = false
  shadow:enabled = false
}

animations:enabled = false

monitor = eDP-1, 1920x1080, 0x0, 1.2
