bindel = ,XF86MonBrightnessUp, exec, brightnessctl -q -n s +10%
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -q -n s 10%-

exec-once=runapp firefox -P "default" --no-remote --class=cheese

# Battery life preservation
decoration  {
  blur:enabled = false
  shadow:enabled = false
}

animations:enabled = false

monitor = eDP-1, 1920x1080, 0x0, 1.2

xwayland {
  force_zero_scaling = 1
}
