bindel=,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 10%+
bindel=,XF86AudioLowerVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 10%- 

# float_gaps = 4

general {
  col.active_border=rgb(072242) rgb(2A7B9B) 90deg
  col.inactive_border=rgba(595959E6) rgba(000000E6) 30deg
}

windowrule {
  name=vesktop behaviour
  float=on
  match:class=vesktop
  move=12 44
  size=1463 1023
  workspace=1
}       

exec-once=[workspace 1; float; size 1463 1023; move 444 44] firefox
exec-once=vesktop & mprisence & nicotine -s
exec-once=[workspace special:music silent] lollypop
exec-once=bash ~/.files/modules/user/hyprland/raiseonhover.sh
exec-once=sleep 5; hyprctl --batch 'dispatch tagwindow +firefox class:firefox; dispatch tagwindow +vesktop class:vesktop'
